using Deckster.Core.Games.ChatRoom;
using System;
using System.Diagnostics;
using Deckster.Client.Communication;
using Deckster.Core.Protocol;
using Deckster.Core.Games.Common;

namespace Deckster.Client.Games.ChatRoom;

/**
 * Autogenerated by really, really eager small hamsters.
*/

[DebuggerDisplay("ChatRoomClient {PlayerData}")]
public class ChatRoomGeneratedClient(IClientChannel channel) : GameClient(channel)
{
    public event Action<ChatNotification>? PlayerSaid;

    public Task<ChatResponse> ChatAsync(SendChatRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<ChatResponse>(request, cancellationToken);
    }

    protected override void OnNotification(DecksterNotification notification)
    {
        try
        {
            switch (notification)
            {
                case ChatNotification m:
                    PlayerSaid?.Invoke(m);
                    return;
                default:
                    return;
            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
    }
}

public static class ChatRoomGeneratedClientConveniences
{
    public static Task<ChatResponse> ChatAsync(this ChatRoomGeneratedClient self, String message, CancellationToken cancellationToken = default)
    {
        var request = new SendChatRequest{ Message = message };
        return self.ChatAsync(request, cancellationToken);
    }
}

public static class ChatRoomGeneratedClientDecksterClientExtensions
{
    public static GameApi<ChatRoomGeneratedClient> ChatRoom(this DecksterClient client)
    {
        return new GameApi<ChatRoomGeneratedClient>(client.BaseUri.Append("chatroom"), client.Token, c => new ChatRoomGeneratedClient(c));
    }
}
